chat/urls.py
from django.urls import path, re_path


from .views import ThreadView, InboxView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

wrnion/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User


from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', "accounts"))),
    path('messages/', include('chat.urls', "messages")),
    path('', views.landing, name="landing"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Customizing admin texts
admin.site.site_header = 'Wrinion'
admin.site.index_title = 'Welcome to project'
admin.site.site_title = 'Control Panel'

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

templates/chatt/chattry.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'chat/main.css' %}">
{% endblock link %}
{% block content %}
{% include 'partials/nav.html' %}

<div class="chatwindow">
    <div id='chat-items' class="chats">
        {% for chat in object.chatmessage_set.all %}
            {% if chat.user.id is user.id %}
                <p class="text rp">
                    {{chat.message}}
                    <span class="time">12.30pm</span>
                </p>
            {% else %}
                <p class="text in">
                    {{chat.message}}
                    <span class="time">12.31pm</span>
                </p>
            {% endif %}

        {% endfor %}
    </div>
    <div class="send">
      <form id='form' method='POST'> {% csrf_token %}
        <input type="hidden" id="me" value = '{{user.username}}'>
          <input type="text" name="message" id="id_message" required />
          <button class="btn-grad" type="submit">
            <img class="send_icon" src="{% static 'asset/send-24px.svg' %}" alt="" />
          </button>
        </form>
    </div>
</div>
{% endblock content %}
{% block script %}
<script
    src="https://code.jquery.com/jquery-3.5.1.js"
    integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"
></script>
<script>
    $(".ham").click(function () {
      console.log("inham")
      $(".friend").toggleClass("active_frnd");
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js" integrity="sha256-IxGLmHPQulZvYG3Kon9cB4ssL2JZ6EcP+nGHURmJe10=" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script> 
<script>
// websocket scripts
    var chatHistory = document.querySelector(".chats");
    chatHistory.scrollTop = chatHistory.scrollHeight;
    var loc = window.location
    var formData = $('#form')
    var msgInput = $('#id_message')
    var chatHolder = $('#chat-items')
    var me = $('#me').val()
    console.log(formData,msgInput,chatHolder)
    var wsStart = 'ws://'
    if(loc.protocol == 'https:'){
        wsStart = 'wss://'
    }
    var endpoint = wsStart + window.location.host + window.location.pathname
    var socket = new ReconnectingWebSocket(endpoint)
    socket.onmessage = function(e){
        //console.log("message",e)
        var chatDataMsg = JSON.parse(e.data)
        let class_text = ""
        //(chatDataMsg.username === me) ? class_text = "text rp" :  class_text = "text in" 
        if (chatDataMsg.username === me) {
          class_text = "text rp";
        }
        else{
          class_text = "text in" ;
        }
        let chattext = `<p class="${class_text}">
            ${chatDataMsg.message}
            <span class="time">12.30pm</span>
          </p>`
        chatHolder.append(chattext)
        chatHistory.scrollTop = chatHistory.scrollHeight;

    }
    socket.onopen = function(e){
        console.log("open",e)
        formData.submit(function(event){
            event.preventDefault()
            var msgText = msgInput.val()
            // chatHolder.append("<li>"+ msgText + " via " + me +"</li>")
            var finalData = {
                'message': msgText
            }
            socket.send(JSON.stringify(finalData))
            formData[0].reset()
        }) 
    }
    socket.onerror = function(e){
        console.log("error",e) 
    }
    socket.onclose = function(e){
        console.log("close",e) 
    }
</script>

{% endblock script %}